#include "hal_data.h"
#include "adc.h"
#include "SerialCompatibility.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

void delay(int dt) {
    R_BSP_SoftwareDelay(dt, BSP_DELAY_UNITS_MILLISECONDS);
}


/*******************************************************************************************************************//**
 * main() is generated by the RZA3UL Configuration editor and is used to generate threads if an RTOS is used.
 * This function is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    Serial.begin(115200);

    while (true) {
        Serial.println((uint8_t*)"It works!");
        double adc_volt;
        int adc_val = analogRead(0, &adc_volt);
        Serial.print((uint8_t*)"ADC0 raw val: "); Serial.println(adc_val);
        Serial.print((uint8_t*)"ADC0 volt val: ");
        Serial.print((int)adc_volt); Serial.print((uint8_t*)"."); Serial.println(((int)(adc_volt * 100)) % 100);
        delay(100);
        adc_val = analogRead(1, &adc_volt);
        Serial.print((uint8_t*)"ADC1 raw val: "); Serial.println(adc_val);
        Serial.print((uint8_t*)"ADC1 volt val: ");
        Serial.print((int)adc_volt); Serial.print((uint8_t*)"."); Serial.println(((int)(adc_volt * 100)) % 100);
        delay(500);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Initialize MMU. */
        R_MMU_Open (&g_mmu_ctrl, &g_mmu_cfg);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
    }
}
